### PR TITLE
Collapsed nav bar

### PR DESCRIPTION
**Pull request by logason**
Collapse items in the nav bar + a little face lift ✨

### CODE REVIEW

**Comment by hugihlynsson** [comment]
#### 📝Changed routes:


| [**/index.module**](https://docs-k1s3j0dj1.avo-dev.app/index.module) | [**/**](https://docs-k1s3j0dj1.avo-dev.app/) |
|:-:|:-:|
|<a href="https://docs-k1s3j0dj1.avo-dev.app/index.module">Screenshot of /index.module</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/xhBe5zYyQzlQ0B8MmG3QMUGdFdb0Un1OaXf7R6-JKpwvWtEacWOBlPrgkHvXaNKc4T6JzPqLHSruF9TudHcULg.png">(view full size)</a> |<a href="https://docs-k1s3j0dj1.avo-dev.app/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/yCRgCBz6lst10xtDEWQP55_oMkdHUgZKYindXVf0XGCZ1p2KIK9QakwdaQ3LhYF5tydko6sq_FTYkqRpUaygJg.png">(view full size)</a> |







Commit 0d68df0fee61c577ac1acce00b4b6f03001d94b3 (https://docs-k1s3j0dj1.avo-dev.app).

**Comment by alex-tpom6oh** [comment]
Looks great! Would be cool to also expend the contents if user is linked to a nested doc, but probably not necessary in this pr

**Review by alex-tpom6oh — APPROVED** [review]

**Review by hugihlynsson — COMMENTED** [review]
Woha! Looking tidy! Here is a quick UX review:

It looks like for some pages, the nav doesn't expand the correct section upon opening a page. Like this one: https://docs-git-collapsed-nav-bar.avo-dev.app/explore-tracking-plan/issue-types-in-inspector
Screenshot 2021-07-15 at 09 52 36
Could it be that this only affects the dev build?

I noticed that expanding and collapsing the _Data Design_ section can get a little slow, presumably because it has the most items. Could we optimise how er calculate the sub-navs?

The expansion state triangles on the right of the sub-groups don't feel quite intuitive nor interactive to me. Also: Should the top-level items a similar indicator too?

Sub-groups are not highlighted when you're in a child page but the top-level group is. That feels a bit unexpected:
Screenshot 2021-07-15 at 10 03 10

**Comment by logason** [comment]
Thank y'all for a great review!

> Looks great! Would be cool to also expend the contents if user is linked to a nested doc, but probably not necessary in this pr

> It looks like for some pages, the nav doesn't expand the correct section upon opening a page. Like this one: https://docs-git-collapsed-nav-bar.avo-dev.app/explore-tracking-plan/issue-types-in-inspector

> Sub-groups are not highlighted when you're in a child page but the top-level group is. That feels a bit unexpected:

Great catch! Looks like my `isActive` check was to naive for the current all-over-the-place URL structure. A recursive check added in e845e31  seems to have fixed the issue!

> I noticed that expanding and collapsing the Data Design section can get a little slow, presumably because it has the most items. Could we optimise how er calculate the sub-navs?

I was hoping this was only the case in dev :/ I'm about to restructure all of these sections, breaking them up into new ones. Should we revisit this if it persists as a problem for the new sections?

> The expansion state triangles on the right of the sub-groups don't feel quite intuitive nor interactive to me.

Any suggestions on how we might improve that @hugihlynsson?

> Also: Should the top-level items a similar indicator too?

I didn't feel like that being necessary because all of them are expandable, while only handful of the sub-navs are and therefor they required some sort of expectation management / differentiation from the non-expandable routes. I took some inspo from Segment's docs where this pattern feels quite natural. What do you think @hugihlynsson?

**Review by hugihlynsson — APPROVED** [review]
✨

**Pull request merged**
