### PR TITLE
Moved "get your tracking plan into avo" under import, export and publishing

### PR DESCRIPTION
**Pull request by thoragudf**
…ishing.

### CODE REVIEW

**Comment by hugihlynsson** [comment]
#### 📝 Changed routes:


| [**/audit/_meta**](https://docs-9bmxmrii6.avo-dev.app/audit/_meta) | [**/audit/quickstart**](https://docs-9bmxmrii6.avo-dev.app/audit/quickstart) |
|:-:|:-:|
|<a href="https://docs-9bmxmrii6.avo-dev.app/audit/_meta">Screenshot of /audit/_meta</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/3ezfmg6ebVyjB_NrNFy_NX0gYJhf7gBRElUSTXqkyDouGP4hyxVRlVG6mhtDhMHoZakdQR__AN3arukpa22YXw.png">(view full size)</a> |<a href="https://docs-9bmxmrii6.avo-dev.app/audit/quickstart">Screenshot of /audit/quickstart</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/wzA6OCfWBB9ajTpwUegDC6nsN7W-XIIwjkzh0fH-cCquY7e1Q9pP9xmLkdew-LFZrROlXWqBssSuVXSUKz0ABQ.png">(view full size)</a> |



| [**/publishing/_meta**](https://docs-9bmxmrii6.avo-dev.app/publishing/_meta) | [**…tracking-plan-into-avo**](https://docs-9bmxmrii6.avo-dev.app/publishing/get-tracking-plan-into-avo) |
|:-:|:-:|
|<a href="https://docs-9bmxmrii6.avo-dev.app/publishing/_meta">Screenshot of /publishing/_meta</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/jAoC7DOxVSTjMKigRFFr2nSc5FbCVXe6EgrIeUYn5IEk0fb86p2kbM13orB8RpulXNU_cRhIRu6vB747rUeUrg.png">(view full size)</a> |<a href="https://docs-9bmxmrii6.avo-dev.app/publishing/get-tracking-plan-into-avo">Screenshot of /publishing/get-tracking-plan-into-avo</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/mmpBMy718pP8SZmNAnCKxgccsakfXbR7pb_wgHYlDF5DtoTrKSphkeiD_V4Yw0Lw7RtOcoz3Oylf_28cO_LH-g.png">(view full size)</a> |







Commit 4eb8639098f78e05c8497382eb758c41a7566506 (https://docs-9bmxmrii6.avo-dev.app).

**Comment by thoragudf** [comment]
I can't get the redirects to work. Do you know what I'm doing wrong @hugihlynsson ?

**Comment by hugihlynsson** [comment]
> I can't get the redirects to work. Do you know what I'm doing wrong @hugihlynsson ?

I just tried it and they seem to work!

**Comment by thoragudf** [comment]
Wow i completely forgot about this one @klaraavo do you want to review? Or @hugihlynsson ?

**Review by hugihlynsson — APPROVED** [review]
LGTM!

**Pull request merged**
