### PR TITLE
Update ref to correct uri

### PR DESCRIPTION
**Pull request by bjornj12**
Fixing URI Links that are returning sites that are 4xx errors, to increase our Ahref score

### CODE REVIEW

**Comment by hugihlynsson** [comment]
#### 📝 Changed routes:


| [**…urces-and-destinations**](https://docs-orznn216z.avo-dev.app/data-design/define-sources-and-destinations) | [**…e/tracking-plan/events**](https://docs-orznn216z.avo-dev.app/workspace/tracking-plan/events) |
|:-:|:-:|
|<a href="https://docs-orznn216z.avo-dev.app/data-design/define-sources-and-destinations">Screenshot of /data-design/define-sources-and-destinations</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/qObCix4nMkWXNxDr4QKM652ffj2KUpRBPKOunwYEYjRO9ziuqzwq3vOI9u4VaOaFYsH63rKGXpK1yzLy6cgZog.png">(view full size)</a> |<a href="https://docs-orznn216z.avo-dev.app/workspace/tracking-plan/events">Screenshot of /workspace/tracking-plan/events</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/j5ofF64LiAeN586pasXxvWq503s0sWXOP3xrIP8cSQ8XxUbitWSz1WsGSR0wLfj_LNjr5T4M-DcIBHPMGQWzyQ.png">(view full size)</a> |







Commit 9a3eff049937d4c1e3687c09defa0e1b77b466c3 (https://docs-orznn216z.avo-dev.app).

**Comment by bjornj12** [comment]
Both new URIS work nicely now 👍

**Review by logason — APPROVED** [review]
Nice! So Ahrefs is catching broken links in our docs? 🤯

**Comment by bjornj12** [comment]
> Nice! So Ahrefs is catching broken links in our docs? 🤯

Yep!

**Pull request merged**
