### PR TITLE
Updated approval workflows docs

### PR DESCRIPTION
**Pull request by thoragudf**
The purpose of this branch changed slightly. Added documentation about our branch statuses. I couldn't see that we had any previously.

### CODE REVIEW

**Comment by hugihlynsson** [comment]
#### 📝 Changed routes:


| [**…hes/approval-workflows**](https://docs-9dpx46f2e.avo-dev.app/data-design/branches/approval-workflows) |
|:-:|
|<a href="https://docs-9dpx46f2e.avo-dev.app/data-design/branches/approval-workflows">Screenshot of /data-design/branches/approval-workflows</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/Uh8d-0HLHG_4Sjobj4kgNJxcjw1WRGVcTK79fp495S3ll3nMi5PEwORkl2sWRqHPF-4UDy7bax2bjf2WqHZQ5w.png">(view full size)</a> |







Commit 114b7038456e495e568fbc3a3634da913f8b10ef (https://docs-9dpx46f2e.avo-dev.app).

**Comment by thoragudf** [comment]
Hmm failed spellcheck event though it works on my machine. Am I a developer now?

**Comment by thoragudf** [comment]
> Hmm failed spellcheck event though it works on my machine. Am I a developer now?

Never mind. I'm an idiot. Fixed

**Review by hugihlynsson — APPROVED** [review]
LGTM!

**Pull request merged**
