### PR TITLE
Update faq.mdx

### PR DESCRIPTION
**Pull request by kelsey-fecho**
Updating with the Yes, You Can! framework.

### CODE REVIEW

**Comment by thoragudf** [comment]
@valtyr @logason  "A team member needs to acccept the deployement" – how can we fix?

**Comment by valtyr** [comment]
Anyone who's a member of our Vercel team can accept deployments. I think Hugi and Sölvi are both members.

**Comment by valtyr** [comment]
The root cause of this problem though, is that Kelsey isn't a part of out GitHub organization... so she's submitting PRs through her own fork of the project, rather than directly branching off avohq/docs:master.

**Comment by thoragudf** [comment]
Ahhh... I seeeee – we should fix that then. Thank you @valtyr

**Pull request merged**
