### PR TITLE
Code changes docs

### PR DESCRIPTION
**Pull request by bjornj12**
Drafting up docs for code-changes screen and code snippets

### CODE REVIEW

**Comment by hugihlynsson** [comment]
#### 📝 Changed routes:


| [**/workspace/code-changes**](https://docs-pw62qngwa.avo-dev.app/workspace/code-changes) |
|:-:|
|<a href="https://docs-pw62qngwa.avo-dev.app/workspace/code-changes">Screenshot of /workspace/code-changes</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/oGhYZ-w9b37LBgGtL4eTU4x5MiaNXquA_G3yJ7X3eGnF8nGPc2Hyu4un8JfaByx_pizTyqa0l24pfCY9NgfGZA.png">(view full size)</a> |







Commit 4c2ea649452a6dfe5d5a30eb31e4980f6324be39 (https://docs-pw62qngwa.avo-dev.app).

**Comment by bragur** [comment]
I'm getting a application error when viewing the deployment 😬

**Comment by hugihlynsson** [comment]
@bjornj12 I merge main into the branch and it looks like the Vercel build works now 🎉

**Comment by hugihlynsson** [comment]
I'm not sure what's happening but I don't think it's this branches fault (it happens on every page). I think we should go ahead and merge it and monitor production for issues.

**Review by hugihlynsson — APPROVED** [review]

**Comment by bjornj12** [comment]
I´d love to put space between these images, not sure how to get that in

image

**Comment by hugihlynsson** [comment]
> I´d love to put space between these images, not sure how to get that in

I guess you could just add a `<div style="height: 20px" />` or something like that?

**Comment by bjornj12** [comment]
image 🙏

**Pull request merged**
