### PR TITLE
Added name mapping docs for property per event.

### PR DESCRIPTION
**Pull request by thoragudf**

### CODE REVIEW

**Comment by hugihlynsson** [comment]
#### 📝 Changed routes:


| [**/data-design/name-mapping**](https://docs-i85mi9v89.avo-dev.app/data-design/name-mapping) |
|:-:|
|<a href="https://docs-i85mi9v89.avo-dev.app/data-design/name-mapping">Screenshot of /data-design/name-mapping</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/w2Bo7Qeviq9HcCHE5eKd1CU-86A-OCFAXMKM1Z4GcDm3JnNrUyn2Y9HjYfvZGrJpV6maGYAH9BKQtG66HmKQ3A.png">(view full size)</a> |







Commit 39da39d908d4ae0a77d526bcf3bdbbdb4651608a (https://docs-i85mi9v89.avo-dev.app).

**Review by hugihlynsson — APPROVED** [review]
👌

**Comment by alex-tpom6oh** [comment]
Yes, run `yarn fix-spelling` in the root and then add the thing to ignored list, then commit updated `.spelling` file

**Comment by logason** [comment]
One more thing I think is worth mentioning in this doc is the name mapping priority (in the case where multiple name mappings are defined for the same property name) we use both in the implementation instructions and Avo Functions.

The priority is as follows. The first available mapping in this list is the one that is used:
1. Event specific, destination specific
2. Event specific, all destinations
3. Global for all events, destination specific
4. Global for all events, all destinations

**Comment by thoragudf** [comment]
Sweet, thank you for your input @alex-tpom6oh @hugihlynsson and @logason . I ignored the file name using Alex's trick and added the priority suggested by Sölvi.

**Pull request merged**
