### PR TITLE
Update GitHub action node version

### PR DESCRIPTION
**Pull request by hugihlynsson**

### CODE REVIEW

**Comment by hugihlynsson** [comment]
@logason the _build (12.x)_ check is stuck on this PR, probably from when GitHub was having issues with their actions last week. Is there a way to merge this PR?

**Review by bragur — APPROVED** [review]

**Comment by logason** [comment]
> @logason the _build (12.x)_ check is stuck on this PR, probably from when GitHub was having issues with their actions last week. Is there a way to merge this PR?

Hmm great question, clicked rerun on the job here: https://github.com/avohq/docs/actions/runs/2051795541

**Comment by logason** [comment]
> > @logason the _build (12.x)_ check is stuck on this PR, probably from when GitHub was having issues with their actions last week. Is there a way to merge this PR?
> 
> Hmm great question, clicked rerun on the job here: https://github.com/avohq/docs/actions/runs/2051795541

Well, that did not change anything 🙃

**Comment by logason** [comment]
No idea how to get rid of that hah, maybe just create a new PR? 🤷

**Comment by hugihlynsson** [comment]
> No idea how to get rid of that hah, maybe just create a new PR? 🤷

I've tried that and also creating a new branch and creating a new PR from that, the stuck build is still there 🤡

**Comment by hugihlynsson** [comment]
It looks like this is a GitHub bug. @logason is there a way to get around the disabled merge button and just get this on master?

**Comment by logason** [comment]
> It looks like this is a GitHub bug. @logason is there a way to get around the disabled merge button and just get this on master?

Disabled the rule for all checks to pass before merge, looks like the job disappeared 🤔 

Anyways, merging this PR now and re-enabling the rule.

**Pull request merged**
